<a href="https://colab.research.google.com/github/rahul-bellam/nlp/blob/main/nlp_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('/content/IMDB Dataset.csv')
#comma seperated file

In [5]:
data.head(10)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [6]:
data.tail(10)

review sentiment
49990  Lame, lame, lame!!! A 90-minute cringe-fest th...  negative
49991  Les Visiteurs, the first movie about the medie...  negative
49992  John Garfield plays a Marine who is blinded by...  positive
49993  Robert Colomb has two full-time jobs. He's kno...  negative
49994  This is your typical junk comedy.<br /><br />T...  negative
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [12]:
#names of columns
data.columns

Index(['review', 'sentiment'], dtype='object')

In [13]:
#check if there is any null value
data.isnull().any()

review       False
sentiment    False
dtype: bool

In [15]:
#shape of data
data.shape

(50000, 2)

In [16]:
#number of null values
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [17]:
#data descriprion(statisticals)
data.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [18]:
# value counts of each type
data['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

text normalization

tokenization

In [21]:
pip install matplotlib

In [26]:
#libraries for
import seaborn as sns #data visualization
import matplotlib.pyplot as plt #data visualization
import nltk #for nlp
from sklearn.feature_extraction.text import CountVectorizer #bag of words
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelBinarizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from wordcloud import WordCloud, STOPWORDS
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem.porter import PorterStemmer
from wordcloud import WordCloud, STOPWORDS
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize, sent_tokenize

In [27]:
import spacy
import re, string, unicodedata
from nltk.tokenize.toktok import ToktokTokenizer
from nltk.stem import LancasterStemmer, WordNetLemmatizer
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn. naive_bayes import MultinomialNB
from sklearn.svm import SVC
from textblob import TextBlob
from textblob import Word
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from bs4 import BeautifulSoup

In [28]:
#for removing stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [30]:
#tokenization
tokenizers=ToktokTokenizer()
#setting stopwords to english
stopwords=nltk.corpus.stopwords.words('english')

In [33]:
#remove html tags and remnants
def noiseremoval_text(text):
  soup=BeautifulSoup(text, "html.parser") #data cleaning
  text=soup.get_text()
  text=re.sub('\[[^]]*\]', '', text)
  return text

In [36]:
#apply function on review coloumn
data['review']=data['review'].apply(noiseremoval_text) #lambda function

<ipython-input-33-7282149ad34c>:3: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup=BeautifulSoup(text, "html.parser") #data cleaning


In [37]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

**stemming**

In [39]:
#stemming the text
def stemmer(text):
  ps=nltk.porter.PorterStemmer() # function call
  text=' '.join([ps.stem(word) for word in text.split()]) #stemmer doing its job
  return text

In [40]:
data['review']=data['review'].apply(stemmer)

In [41]:
data.head()

review sentiment
0  one of the other review ha mention that after ...  positive
1  a wonder littl production. the film techniqu i...  positive
2  i thought thi wa a wonder way to spend time on...  positive
3  basic there' a famili where a littl boy (jake)...  negative
4  petter mattei' "love in the time of money" is ...  positive

Removing stopwords

In [52]:
def removing_stopwords(text, is_lower_case=False):
  #tokenization of text
  tokenizers=ToktokTokenizer()
  #setting stopwords to english
  tokens=tokenizers.tokenize(text)
  tokens = [i.strip() for i in tokens]
  if is_lower_case:
    filtokens = [i for i in tokens if i not in stopwords] # if a token is in lower case check if it is in stopwords dataset
  else:
    filtokens = [i for i in tokens if i.lower() not in stopwords] # if a token is not in lower case, convert to lower case and check for stopwords datset
  filtered_texts = ' '.join(filtokens)
  return filtered_texts

In [53]:
# apply
data['review']=data['review'].apply(removing_stopwords)

In [54]:
data.head()

review sentiment
0  one review ha mention watch 1 oz episod ' hook...  positive
1  wonder littl production. film techniqu veri un...  positive
2  thought thi wa wonder way spend time hot summe...  positive
3  basic ' famili littl boy ( jake ) think ' zomb...  negative
4  petter mattei ' " love time money " visual stu...  positive

TRAIN AND TEST DATA

In [55]:
#split the datset
#train the dataset
train_reviews_data=data.review[:30000]
#test dataset
test_reviews_data=data.review[30000:]

BAG of WORDS TECHNIQUE

In [59]:
#count vectorizer for bag of words
cv=CountVectorizer(min_df=0.0, max_df=1.0, binary=False, ngram_range=(1,3))
#transformed train reviews
cv_train=cv.fit_transform(train_reviews_data)

In [60]:
print('Bag of words model:> Train')
print(cv_train.shape)

Bag of words model:> Train
(30000, 5543493)


In [62]:
print('Bag of words model:> Test')
cv_test=cv.transform(test_reviews_data)
print(cv_test.shape)
#vocab=cv.get_feature_names()-toget feature names

Bag of words model:> Test
(20000, 5543493)


TF-IDF TECHNIQUE

In [63]:
#tf-idf vectorizer
tf=TfidfVectorizer(min_df=0.0, max_df=1.0, ngram_range=(1,3))
#transformed train reviews
tf_train=tf.fit_transform(train_reviews_data)

In [64]:
#transformed test reviews
tf_test=tf.transform(test_reviews_data)

In [65]:
print('TF-IDF model:> Train')
print(tf_train.shape)
print('TF-IDF model:> Test')
print(tf_test.shape)

TF-IDF model:> Train
(30000, 5543493)
TF-IDF model:> Test
(20000, 5543493)


LABEL ENCODING

In [66]:
#label encoding
label=LabelBinarizer()
#transformed sentiment data
sentiment_data=label.fit_transform(data['sentiment'])
print(sentiment_data.shape)

(50000, 1)


In [67]:
sentiment_data

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [68]:
train_data=sentiment_data[:30000]
test_data=sentiment_data[30000:]

In [69]:
#training the model

In [70]:
logistic=LogisticRegression(penalty='l2', max_iter=500, C=1, random_state=42)
#fitting the model for Bag of Words
lr_bow=logistic.fit(cv_train, train_data)
print(lr_bow)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, max_iter=500, random_state=42)


In [71]:
#predict with bag of words
bow_predict=logistic.predict(cv_test)
print(bow_predict)

[1 0 0 ... 1 0 0]


In [72]:
#accuracy of bow
lr_bow_score=accuracy_score(test_data, bow_predict)
print('lr_bow_score:> ', lr_bow_score)

lr_bow_score:>  0.89285


In [73]:
#fitting tf-idf
lr_tfidf=logistic.fit(tf_train, train_data)
print(lr_tfidf)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, max_iter=500, random_state=42)


In [74]:
#predict with tf-idf
tfidf_predict=logistic.predict(tf_test)
print(tfidf_predict)

[1 0 0 ... 1 0 0]


In [75]:
#accuracy with tf-idf
lr_tfidf_score=accuracy_score(test_data, tfidf_predict)
print('lr_tfidf_score:> ', lr_tfidf_score)

lr_tfidf_score:>  0.879


**we have done sentiment analysis of an imdb datset of 50000 reviews on different shows and movies we have got good accuracy with both bag of words and tf-idf techniques

but in the course i saw they got better accuracy with tf-idf but here i got better with bag of words**
 i think i should learn implementation more perfectly and learn many more models